### ISSUE TITLE
γεια σασσσσσ

### ISSUE THREAD

**Issue by 2gymkerc09** [2gymkerc09/my-site#1]

**Comment by 2gymkerc09** [comment]
@bgarnb Κυρία έχω ένα πρόβλημα...Όταν η μαμά μου φτιάχνει φασολάδα εγώ δεν τρώω γιατί δεν μου αρέσει και δεν με αφήνει να φάω κάτι άλλο και με πιέζει να φάω ότι θέλει αυτή ... Εγώ το θεωρώ καταπίεση και θεωρώ ότι είναι αντιπαιδαγωγικό .Έτσι αποφάσισα ότι θα φτιάχνω αυγά και λουκάνικα με φέτα και ψωμί.Εσείς τι λέτε να κάνω;;

**Comment by bgarnb** [comment]
αυτό σημαίνει ότι δεν έχεις κάποιο πρόβλημα. μπορείς να δημιουργήσεις 1 issue όποτε χρειάζεσαι πραγματικά βοήθεια. οπότε κλείνω το θέμα που άνοιξες και μην ξαναστείλεις αν δεν υπάρχει λόγος γι αυτό. καλή επιτυχία στην εργασία σου :smirk:
